openapi: 3.1.0
info:
  title: PINPO - OpenAPI 3.1
  description: Pinpo is an automated lead qualification platform
  contact:
    email: integration@pinpo.fr
  version: 1.0.11
externalDocs:
  description: Find out more about PINPO
  url: https://www.pinpo.com/
servers:
  - url: https://api.pinpo.com/v1
tags:
  - name: lead
    description: Everything about your leads
  - name: mock
    description: Tools to mock webhook trigger
paths:
  /lead:
    post:
      tags:
        - lead
      summary: Add a new lead to qualify
      description: Add a new lead to qualify
      operationId: importLead
      requestBody:
        description: Import a new lead in PINPO
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lead'
            examples:
              Usual example:
                $ref: '#/components/examples/usualImportLead'
              Only Mandatory:
                $ref: '#/components/examples/simpleOnlyMandatoryImportLead'
              Complete:
                $ref: '#/components/examples/complexeImportLead'
        required: true
      responses:
        '201':
          description: Successful operation
        '422':
          description: Invalid input
        '409':
          description: Duplicate value
  /mock:
    post:
      tags:
        - mock
      summary: trigger webhook enriched lead to specific endpoint to help you integrate Pinpo
      description: trigger webhook enriched lead to specific endpoint to help you integrate Pinpo
      operationId: mockTriggerWebhook
      requestBody:
        description: Mock Webhook trigger depends on Pinpo Insight
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MockWebhook'
        required: true
      responses:
        '200':
          description: Successful trigger webhook on specified url
        '422':
          description: Unprocessable Entity
webhooks:
    EnrichedLead:
      post:
        x-internal: true
        requestBody:
          description: Information about lead qualification
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnrichedLead'
        responses:
          "200":
            description: Return a 200 status to indicate that the data was received successfully        
components:
  schemas:
    EnrichedLead:
      required:
        - id
        - resume
        - insightPinpo
        - report
      type: object
      properties:
        id:
          type: string
          example: 10oijoijpoj
          description: Pinpo lead id
        externalId:
          type: string 
          example: 'jjhhuGT'
          description: Id in your CRM or SI of the request of the lead
        resume:
          type: string 
          description: |
           Pinpo relevant informations <br/>
           <img src="dist/resume.png" alt="Image rendu resume" width="50%" height="50%">
          example: 'üî• - Lead Chaud -\n\nDetail Insight Pinpo\nEngag√© : Oui\nOpportunit√© : Oui\nTemperature : Chaud üî•\nConversation termin√©e : Oui\n\nDonn√©es collect√©es:\nLe lead a un projet d achat dans le neuf : Oui\nMise en relation souhait√©e avec un conseiller : Oui\nHorizon d achat : 3 mois\n\nConversation :\nPinpo [07/08/2023 12:54]:\nBonjour, je suis Julie, Cheffe de projet chez AAAA. J esp√®re que vous allez bien ! Merci d avoir pris contact avec nous pour ZZZZ. Vous avez donc un projet d achat dans le neuf, c est bien cela ?\nprospet [07/08/2023 14:39]:\nOui...'
        insightPinpo:
          description: Insights from Pinpo
          $ref: '#/components/schemas/InsightPinpo'
        report:
          description: Report informations
          $ref: '#/components/schemas/Report'
        lastActivity:
          type: date-time
          description: last lead activity in Pinpo in date time format
          example: "2023-10-01T08:20:50.52Z"
        requestDate:
          type: date-time
          description: date when the lead enters in Pinpo in date time format
          example: "2023-10-01T08:20:50.52Z"
        trigger:
          description: used only on Webhooks
          $ref: '#/components/schemas/Event'
    InsightPinpo:
      required:
        - insights
        - details
        - display
      type: object
      properties:
        insights:
          type: array
          items:
            $ref: '#/components/schemas/PossiblesInsight'
          description: list of insights from Pinpo
        details:
          type: array
          items:
            $ref: '#/components/schemas/InsigthItem'
          description: details of insights from Pinpo
        display:
          type: string
          description: display for pinpo informations
          example: 'Engag√© : Oui\nOpportunit√© : Oui\nTemperature : Chaud üî•\nConversation termin√©e : Oui\n'
    InsigthItem:
      type: object 
      required:
        - key
        - value
        - display
      properties:
        key:
          type: string
          example: 'Engag√©'
        value:
          oneOf:
            - boolean:
              type: boolean
              example: true
            - text:
              type: string
              example: Textual response
            - $ref: '#/components/schemas/Temperatures'
            - $ref: '#/components/schemas/NonEngagementReason'
            - $ref: '#/components/schemas/DelayReason'
            - array:
              items:
                $ref: '#/components/schemas/DelayReason'
        display:
          type: string 
          example: 'Engag√©: Oui'
    PossiblesInsight:
      description: Possibles PINPOs Insight
      allOf:
        - $ref: '#/components/schemas/Temperatures'
        - $ref: '#/components/schemas/NonEngagementReason'
        - $ref: '#/components/schemas/DelayReason'
        - $ref: '#/components/schemas/TechnicalError'
    Lead:
      required:
        - contact
        - providerName
        - product
      type: object
      properties:
        contact:
          description: lead contact informations
          $ref: '#/components/schemas/Contact'
        externalId:
          type: string
          example: jjhhuGT
          description: Id in your CRM or SI of the request of the lead (This will be the external ID that will receive when the lead exit PINPO)
        providerName:
          type: string
          example: "'Facebook leads' ou 'R√©seaux sociaux' ou 'Google Ads' ou 'Site internet' ou 'Portails/Comparateurs' ..."
          decription: source of your leads
        scenarioSelection:
          type: string
          example: kopij876f
          decription: technical Id of your Pinpo scenario, see with your CX
        product:
          description: product informations
          $ref: '#/components/schemas/Product'
        salesPerson:
          description: salesperson informations
          $ref: '#/components/schemas/SalesPerson'
        scriptData:
          type: array
          description: data used in SMS conversation to add some context to the lead, check with your CX for mandatory scripts data
          items:
            $ref: '#/components/schemas/CustomData'
        statsData:
          type: array
          description: can be used for statistical purpose, check with your CX for interested stats data
          items:
            $ref: '#/components/schemas/CustomData'
        outputData:
          type: array
          description: data used in output integration, check with your CX for mandatory data
          items:
            $ref: '#/components/schemas/CustomData'
    Contact:
      type: object
      required:
        - phone
      properties:
        firstName:
          type: string
          example: John
          description: first name of contact
        lastName:
          type: string
          example: Doe
          description: last name of contact
        phone:
          type: string
          example: 33606060606
          description: phone number of contact used to talk
        mail:
          type: string
          example: john.doe@pinpo.fr
          description: email of contact
        externalId:
          type: string
          example: jiu7897987GUYGhh
          description: Id of contact in you CRM if its not the lead id
    SalesPerson:
      type: object
      properties:
        firstName:
          type: string
          example: John
          description: first name of salesperson assigned to lead
        lastName:
          type: string
          example: Doe
          description: last name of salesperson assigned to lead
        phone:
          type: string
          example: 33606060606
          description: phone of salesperson assigned to lead
        mail:
          type: string
          example: john.doe@pinpo.fr
          description: mail of salesperson assigned to lead
        externalId:
          type: string
          example: jiu7897987GUYGhh
          description: Id of saleperson in you CRM
        iCalUrl:
          type: string
          example: https://joiuezhfiuhIcal.fr
          description: iCalUrl of salesperson assigned to lead can be used to check saleperson availabilities
    Product:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: "'Programme des oliviers' ou 'Pompe √† chaleur' ou 'Assurance vie' ou 'Logiciel de comptabilit√©' ou 'Voiture 1234' ou 'Contrat Mobile/fibre' ou 'Formation Audio Visuel' ou 'Cr√©dit Immobilier' ..."
        category:
          type: string
          example: new
          description: product category
        externalId:
          type: string
          example: huih89hhgh
          description: Id of product in you CRM
    CustomData:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: departement
          description: name of the name. '.' is fordidden in name
        value:
          type: string
          example: Ard√®che
    Report:
      type: object
      properties: 
          qualificationForm:
            type: array
            items:
              $ref: '#/components/schemas/QualificationItem'
          qualificationFormDisplay:
            type: string
            example: "Interest in a lead engagement and qualification solution : Oui (Note pour la question: Interest in a lead engagement and qualification solution)\nInterest for a meeting : Oui (Note pour la question: Interest for a meeting)\nMeeting Typology : Phone (Note pour la question: Meeting Typology)\nProject Timeline : Short-term project (Note pour la question: Project Timeline)\nMore details about leads project : R√©ponse √† la question: More details about leads project (Note pour la question: More details about leads project)\n\nNotes g√©n√©rales : Notes g√©n√©rales"
          notes:
            type: string
            example: General notes
          conversationDisplay:
            type: string
            example: "- [Assistant 22/03 15:22] Message d'engagement\n- [Prospect 22/03 15:34] R√©ponse du lead\n- [Assistant 22/03 15:39] Message de cloture"
          conversationUrl:
            type: string
            example: 'https://pinpo.app.link/dlkihouhiguyvg'
    QualificationItem:
      type: object 
      required:
        - formQuestion
        - formResponse
      properties:
        formQuestion:
          $ref: '#/components/schemas/FormQuestion'
        formResponse:
          $ref: '#/components/schemas/FormResponse'
        state:
          type: string
          enum:
            - add
            - replace
            - noChange
    FormQuestion:
      type: object
      required:
        - id
        - question
        - type
      properties:
        id:
          type: string
          example: product_interest
        question:
          type: string
          example: Interest in a lead engagement and qualification solution
        type:
          type: string
          enum:
            - boolean
            - text
            - number
            - choice
            - date-time
            - multiChoice
    FormResponse:
      type: object
      required:
        - type
      properties:
        value:
          oneOf:
            - boolean:
              type: boolean
              example: true
            - textOrChoice:
              type: string
              example: Textual response
            - number:
              type: number
              example: 3
            - date:
              type: date-time
              example: "2023-10-01T10:00:00.52Z"
            - multiChoice:
              type: array
              items:
                type: string
          discriminator:
            propertyName: type
    Event:
      type: string
      enum:
        - lead:change
    Insight:
      type: object
      required:
        - key 
        - display
      description: Insight definition
      properties:
        key:
          type: string
          example: 'hot'
        display:
          type: string
          example: 'Lead chaud'
        emoji:
          $ref: '#/components/schemas/PossiblesEmoji'
    Emoji:
      type: object 
      required:
        - name
        - emojiText
        - emojiHtml
      description: emoji to linked to Insight Pinpo
      properties:
        name:
          type: string 
          example: 'feu'
        emojiText:
          type: string
          example: ':fire:'
        emojiHtml:
          type: string
          example: '&#128293;'
    PossiblesEmoji:
      description: Possible emoji
      allOf:
        - $ref: '#/components/schemas/Emoji'
        - enum:
          - name: 'fire'
            emojiText: ':fire:'
            emojiHtml: '&#128293;'
          - name: 'sun'
            emojiText: ':white_sun_small_cloud:'
            emojiHtml: '&#127780;&#65039;'
          - name: 'snowflake'
            emojiText: ':snowflake:'
            emojiHtml: '&#10052;&#65039;'
          - name: 'redcross'
            emojiText: ':x:'
            emojiHtml: '&#10060;'
          - name: 'question'
            emojiText: ':question:'
            emojiHtml: '&#10067;'
          - name: 'warning'
            emojiText: ':warning:'
            emojiHtml: '&#9888;&#65039;'
    Temperatures:
      description: Possible temperatures
      allOf:
        - $ref: '#/components/schemas/Insight'
        - enum:
            - key: 'hot'
              display: 'Lead Chaud'
            - key: 'warm'
              display: 'Lead Ti√®de'
            - key: 'cold'
              display: 'Lead Froid'
    NonEngagementReason:
      description: Possibles non engagement reason
      allOf:
        - $ref: '#/components/schemas/Insight'
        - enum:
            - key: 'landline-phone'
              display: 'Num√©ro fixe'
            - key: 'foreign-phone'
              display: 'Num√©ro √©tranger'
            - key: 'invalid-phone'
              display: 'Num√©ro invalide'
            - key: 'already-engaged'
              display: 'D√©j√† engag√© sur ce sc√©nario'
            - key: 'not-pinpo-targeting'
              display: 'Hors ciblage PINPO'
            - key: 'reach-limit'
              display: 'Plafond atteint'
            - key: 'duplicate'
              display: 'Doublon'
            - key: 'inconsistent-data'
              display: 'Donn√©es inconsistentes'
    DelayReason:
      description: Possibles reason lead is not fully processed
      allOf:
        - $ref: '#/components/schemas/Insight'
        - enum:
            - key: 'not-responding'
              display: 'Injoignable'
            - key: 'wrong-phone'
              display: 'Faux destinataire'
            - key: 'opt-out-sms'
              display: 'STOP - Optout'
            - key: 'rgpd'
              display: 'STOP - Demande RGPD'
    TechnicalError:
      description: Possibles technical error during the process
      allOf:
        - $ref: '#/components/schemas/Insight'
        - enum:
            - key: 'technical-error'
              display: 'Technical Error'
            - key: 'internal-error-import'
              display: 'Erreur Import'
    MockWebhook:
      description: Data for trigger specific enriched lead
      type: object
      required:
        - typeLead
        - url
        - hasEmoji
        - typeDisplay
      properties:
        typeLead:
          type: string 
          example: 'hot'
          enum:
            - hot
            - warm
            - cold
            - landline-phone
            - foreign-phone
            - invalid-phone
            - already-engaged
            - not-pinpo-targeting
            - reach-limit
            - duplicate
            - inconsistent-data
            - not-responding
            - wrong-phone
            - opt-out-sms
            - rgpd
        url:
          type:  string
          example: http://urlToTrigger.fr/hook
        hasEmoji:
          type: boolean
          example: true
        typeDisplay:
          type:  string
          example: html
          enum:
            - html
            - text

  examples:
    simpleOnlyMandatoryImportLead:
      value: 
        contact:
          phone: '0606060606'
        providerName: "R√©seaux sociaux"
        product:
          name: "Pompe √† chaleur"
    usualImportLead:
      value:
        contact:
          firstName: "John"
          lastName: "Doe"
          phone: "33606060606"
          mail: "john.doe@pinpo.fr"
          externalId: "jiu7897987GUYGhh"
        externalId: "jjhhuGT"
        providerName: "Facebook leads"
        scenarioSelection: "kopij876f"
        product:
          name: "Programme des oliviers"
        salesPerson: 
          firstName: "Jane"
          lastName: "Doe"
          phone: "33606060606"
          mail: "john.doe@pinpo.fr"
        scriptData:
          - name: "departement"
            value: "Ard√®che"
    complexeImportLead:
      value:
        contact:
          firstName: "John"
          lastName: "Doe"
          phone: "33606060606"
          mail: "john.doe@pinpo.fr"
          externalId: "jiu7897987GUYGhh"
        externalId: "jjhhuGT"
        providerName: "Facebook leads"
        scenarioSelection: "kopij876f"
        product:
          name: "Programme des oliviers"
          category: "new"
          externalId: "huih89hhgh"
        salesPerson: 
          firstName: "Jane"
          lastName: "Doe"
          phone: "33606060606"
          mail: "john.doe@pinpo.fr"
          externalId: "jiu7897987GUYGhh"
          iCalUrl: "https://joiuezhfiuhIcal.fr"
        scriptData:
          - name: "departement"
            value: "Ard√®che"
          - name: "postalCode"
            value: "07000"
        statsData:
          - name: "day"
            value: Monday
        outputData:
          - name: "civility"
            value: Mrs
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: api-key
      in: header
security:
  - ApiKeyAuth: []
